[workspace]
resolver = "2"
members = [
    "rust",
    "rust/macros",
    "rust/xtask",
    "board/100ask-d1-h-rs",
]

[patch.crates-io]
allwinner-hal = { git = "https://github.com/woshiluo/allwinner-hal", branch = "test/d1" }
allwinner-rt = { git = "https://github.com/woshiluo/allwinner-hal", branch = "test/d1" }
